<?php

class UsersTableSeeder extends Seeder {

   /**
    * Run the database seeding.
    *
    * @return void
    */
    public function run() {

        DB::table('users')->truncate();

        DB::table('users')->insert(array(
            array(
                'email'               => 'example@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Sefa Karagöz',
                'theme'               => 'Slate',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'sseffa',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 999,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example2@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test',
                'theme'               => 'Cosmo',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 45,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example3@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test2',
                'theme'               => 'United',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test2',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 75,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example4@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test3',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test3',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 541,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example5@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test4',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test4',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 174,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example6@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test5',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test5',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 25,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example7@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test6',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test6',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 47,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example8@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test7',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test7',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 36,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example9@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test8',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test8',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 85,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example10@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test9',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test9',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 745,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            ),
            array(
                'email'               => 'example11@example.com',
                'password'            => '$2y$10$BS5LjhZqhukFnDDJTRc8fuHf4hT9CmRzG8JG1XGOwjeW24FRm9xBK',
                'activated'           => 1,
                'name'                => 'Test10',
                'theme'               => 'Default',
                'location'            => 'Turkey',
                'reputation'          => 0,
                'username'            => 'test10',
                'web_site_url'        => 'http://www.sefakaragoz.com',
                'biography'           => 'lorem lipsum...',
                'view_count'          => 1,
                'birthday'            => date('Y-m-d'),
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => date('Y-m-d H:i:s'),
            )
        ));
    }
}
